[package]
name = "ext4fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Forensic-grade ext4 filesystem parser"
license.workspace = true

[features]
default = ["hashing"]
ewf = ["dep:ewf"]
hashing = ["dep:blazehash"]

[dependencies]
bitflags = { workspace = true }
blazehash = { workspace = true, optional = true }
crc = { workspace = true }
ewf = { workspace = true, optional = true }

[lints]
workspace = true
