[package]
name = "ext4fs-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[[bin]]
name = "parse_superblock"
path = "fuzz_targets/parse_superblock.rs"
test = false
doc = false

[[bin]]
name = "parse_inode"
path = "fuzz_targets/parse_inode.rs"
test = false
doc = false

[[bin]]
name = "read_dir"
path = "fuzz_targets/read_dir.rs"
test = false
doc = false

[dependencies]
libfuzzer-sys = "0.4"
ext4fs = { path = "../ext4fs", default-features = false }
